---
- name: Install libraries needed to make tmux
  yum: name={{ item }} state=latest
  with_items:
    - gcc
    - ncurses-devel
    - libevent-devel
    - automake
  become: yes

- name: Clone tmux
  git: repo=git://github.com/tmux/tmux.git
       dest=/tmp/tmux
       version=2.4
  register: tmux

- name: Make tmux
  shell: "{{ item }}"
  args:
    chdir: /tmp/tmux
  with_items:
    - sh autogen.sh
    - ./configure && make
    - make install
  become: yes
  when: tmux.changed

- name: Copy .tmux.conf
  copy:
    src: .tmux.conf
    dest: ~/.tmux.conf
